using MovieRecommendation.Dtos.Auth;
using MovieRecommendation.Dtos.Review;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MovieRecommendation.Dtos.Movie;

public class MovieDetailsDocument : IDocument
{
    private readonly MovieDetailsDto _movieDetailsDto;
    private readonly List<CategoryDto?> _categories;
    private readonly List<ReviewDto?> _reviews;
    private readonly List<UserDto?> _reviewUsers;

    public MovieDetailsDocument(
        MovieDetailsDto movieDetailsDto, List<CategoryDto?> categories, List<ReviewDto?> reviews,
        List<UserDto?> reviewUsers
    )
    {
        _movieDetailsDto = movieDetailsDto;
        _categories = categories;
        _reviews = reviews;
        _reviewUsers = reviewUsers;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(40);
            page.Size(PageSizes.A4);

            // Header with title
            page.Header()
                .AlignCenter()
                .Text(_movieDetailsDto.Title)
                .FontSize(20).Bold();

            // Main content
            page.Content().PaddingVertical(10).Column(col =>
            {
                // Movie details
                col.Spacing(5);
                col.Item().Text($"Description: {_movieDetailsDto.Description ?? "N/A"}");
                col.Item().Text($"Average Rating: {_movieDetailsDto.AverageRating}");
                col.Item().Text($"Duration: {_movieDetailsDto.DurationMins} mins");
                col.Item().Text($"Release Year: {_movieDetailsDto.ReleaseYear?.ToString() ?? "N/A"}");

                // Categories
                col.Item().Height(20);
                if (_categories.Count > 0)
                {
                    col.Item().Text("Categories:").Bold();
                    foreach (var category in _categories)
                    {
                        if (category == null) continue;
                        col.Item().Row(row =>
                        {
                            row.AutoItem().Text("• ");
                            row.RelativeItem().Text(category.Name);
                        });
                    }
                }

                // Reviews section
                col.Item().Height(20);
                if (_movieDetailsDto.ReviewIds.Count > 0)
                {
                    col.Item().Text("Reviews:").Bold();

                    col.Item().Table(table =>
                    {
                        // Columns
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(2); // User
                            cols.RelativeColumn(1); // Rating
                            cols.RelativeColumn(3); // Comment
                        });

                        // Header row
                        table.Header(header =>
                        {
                            header.Cell().Element(CellStyle).Text("User").Bold();
                            header.Cell().Element(CellStyle).Text("Rating").Bold();
                            header.Cell().Element(CellStyle).Text("Comment").Bold();
                        });

                        // Data rows
                        for (int i = 0; i < _reviews.Count; i++)
                        {
                            if (_reviews[i] == null || _reviewUsers[i] == null) continue;
                            table.Cell().Element(CellStyle)
                                .Text(
                                    $"{_reviewUsers[i]?.Name}  {_reviewUsers[i]?.Surname} ({_reviewUsers[i]?.Email})");
                            table.Cell().Element(CellStyle).Text(_reviews[i]?.Rating.ToString());
                            table.Cell().Element(CellStyle).Text(_reviews[i]?.Comment);
                        }
                    });

                    static IContainer CellStyle(IContainer container) =>
                        container
                            .Border(1) // full border
                            .BorderColor(Colors.Grey.Medium)
                            .Padding(5);
                }

                // Pagination info
                col.Item().Height(20);
                if (_movieDetailsDto.Paginate != null)
                {
                    col.Item().AlignRight().Text(
                        $"Page {_movieDetailsDto.Paginate.Page}, showing {_movieDetailsDto.Paginate.Count} reviews per page"
                    ).Italic();
                }
            });

            page.Footer()
                .AlignCenter()
                .Text("Generated By MovieRecommendationAPI");
        });
    }
}